spring:
  application:
    name: sgu-editais-service
  profiles:
    active: docker

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: sgu-editais-service
    prefer-ip-address: true