spring:
  application:
    name: sgu-editais-service
  config:
    import: ""
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5436/editais
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

authClient:
  base-url: http://localhost:8080/auth
