  spring:
    application:
      name: sgu-editais-service
    profiles:
      active: docker

    config:
      import: "configserver:"

    cloud:
      config:
        uri: ${CONFIG_SERVER_URI:http://localhost:8888}
        fail-fast: true
